### ISSUE TITLE
Make Gene Chart More Readable

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/sv.iobio#52]
Focus on a variant and I can see a genes track, but it's empty.

![Screenshot 2024-07-25 at 11 30 35](https://github.com/user-attachments/assets/c6ac9f3b-7274-4ebf-9b58-5302811e52ce)

**Comment by emersonlebleu** [comment]
Changing the title of this. I'm not certain why there was an issue with rendering the SVG in what is above but if we see it again. I made some changes to the genes chart there was a bug in it that was causing some major inefficiencies so it could have been related. 

New Focus: 

- [ ] More aggressively stack the genes so that the names are always readable
- [ ] Allow scrolling if needed to accommodate for this... or maybe change the size
- [ ] I would personally like to see the transcript... at least the mane ... I think it would be nice.

**Comment by emersonlebleu** [comment]
I've added another issue for the last part of this idea. We can think of some ways to reasonably display transcript diagrams.
